### ISSUE TITLE
Unknown layer : Merge

### ISSUE THREAD

**Issue by daoud** [NidhiSalian/DeepLearning-Chatbot#1]
during model upload  intent_predict.py file giving the error 
model = load_model('backup/intent_models/model1.h5')

**Comment by NidhiSalian** [comment]
Hello,

The chatbot project was something I worked on in 2017 and unfortunately, I haven't had the time to update it since then.
It seems the Merge layers have been deprecated in the newer versions of Keras.
I looked up the issue online, and it seems to have been replaced with Concatenate.
Here's a link to the official documentation: https://keras.io/layers/merge/#concatenate
Hope this helps!
